workflows:
  ios-build:
    name: Build unsigned iOS IPA
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
